import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Brand Colors
        'bit-lavender': '#8C52FF',
        'bit-red': '#FF526E',
        'bit-green': '#C5FF52',
        'bit-turquoise': '#52FFE2',
        'bit-marble': '#F6F4F0',
        
        // Design System Colors
        'primary-fixed': '#eaddff',
        'surface-variant': '#e4e2de',
        'tertiary': '#00685a',
        'on-tertiary-container': '#f4fffa',
        'inverse-surface': '#30312e',
        'primary-fixed-dim': '#d1bcff',
        'on-error': '#ffffff',
        'on-secondary-container': '#5b0018',
        'on-error-container': '#93000a',
        'on-surface-variant': '#4a4455',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#ffb2b8',
        'secondary-fixed': '#ffdadb',
        'surface-container-low': '#f5f3ef',
        'on-primary-container': '#fffbff',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#14dfc3',
        'surface-tint': '#7131e3',
        'on-surface': '#1b1c1a',
        'secondary': '#b8193f',
        'background': '#fbf9f5',
        'tertiary-fixed': '#4dfcdf',
        'inverse-on-surface': '#f2f0ec',
        'primary': '#6f2de1',
        'on-secondary-fixed-variant': '#91002c',
        'on-primary': '#ffffff',
        'primary-container': '#884efb',
        'outline-variant': '#ccc3d8',
        'on-primary-fixed': '#24005b',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'surface': '#fbf9f5',
        'surface-container-highest': '#e4e2de',
        'on-primary-fixed-variant': '#5800c8',
        'surface-container-high': '#eae8e4',
        'on-tertiary-fixed-variant': '#005045',
        'inverse-primary': '#d1bcff',
        'outline': '#7b7487',
        'on-tertiary-fixed': '#00201b',
        'surface-container': '#f0eeea',
        'on-secondary-fixed': '#40000e',
        'surface-dim': '#dbdad6',
        'secondary-container': '#fe516d',
        'surface-bright': '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#008472',
        'on-background': '#1b1c1a',
      },
      fontFamily: {
        'headline': ['Playfair Display', 'serif'],
        'body': ['Lexend', 'sans-serif'],
        'label': ['Atkinson Hyperlegible', 'sans-serif'],
        'display': ['Playfair Display', 'serif'],
        'interface': ['Atkinson Hyperlegible', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
